// GENERATED by scripts/build-content.mjs — do not edit.
// Regenerate with `npm run content`.

import type { ContentNode } from "./types";

export const CONTENT_TREE: ContentNode = {
  "slug": "content",
  "name": "Content",
  "path": "/finder",
  "kind": "folder",
  "size": 666,
  "modified": "2026-08-10",
  "children": [
    {
      "slug": "work",
      "name": "Work",
      "path": "/finder/work",
      "kind": "folder",
      "size": 666,
      "modified": "2026-08-10",
      "children": [
        {
          "slug": "example-project",
          "name": "Example Project",
          "path": "/finder/work/example-project",
          "kind": "folder",
          "size": 666,
          "modified": "2026-01-01",
          "meta": {
            "title": "Example Project",
            "role": "Director, Product Design",
            "org": "Example Co",
            "year": 2026,
            "duration": "6 months",
            "team": "4 designers, 9 engineers",
            "tags": [
              "Template",
              "Delete Me"
            ],
            "summary": "Scaffolding that exercises the content pipeline. Replace with a real case study.",
            "outcomes": [
              {
                "label": "Placeholder metric",
                "value": "+00%"
              },
              {
                "label": "Second metric",
                "value": "0x"
              }
            ],
            "featured": false,
            "confidential": false
          },
          "body": "This folder is a **template**, not real work. It exists so the content pipeline\nhas something to render before the real case studies land.\n\nTo add a real project: create a sibling folder, give it an `index.mdx` with the\nfrontmatter above, and add numbered section files. Nothing else needs to change.",
          "children": [
            {
              "slug": "01-problem",
              "name": "Problem",
              "path": "/finder/work/example-project/01-problem",
              "kind": "document",
              "size": 276,
              "modified": "2026-08-10",
              "body": "Sections are ordinary Markdown. The numeric filename prefix sets reading order;\nFinder sorts by name, so you get a narrative sequence without building a stepper.\n\n## Sub-headings work\n\nSo do lists, **emphasis**, `inline code`, and [links](https://smithkipnis.com).\n\n- One\n- Two\n- Three\n\n> Blockquotes render too."
            },
            {
              "slug": "02-approach",
              "name": "Approach",
              "path": "/finder/work/example-project/02-approach",
              "kind": "document",
              "size": 390,
              "modified": "2026-08-10",
              "body": "Video embeds use a `video-embed` tag. Both platforms are supported, and the\nplayer is lazy — it loads only after a click, so a case study with four videos\ndoes not pull four players on open.\n\n<video-embed platform=\"youtube\" id=\"aqz-KE-bpKQ\" title=\"Example YouTube embed\"></video-embed>\n\nSet `platform` to `vimeo` and pass the numeric id for Vimeo:\n\n<video-embed platform=\"vimeo\" id=\"76979871\" title=\"Example Vimeo embed\"></video-embed>\n\nText continues normally after an embed."
            }
          ]
        }
      ]
    }
  ]
};
