// GENERATED by scripts/build-content.mjs — do not edit.
// Regenerate with `npm run content`.

import type { ContentNode } from "./types";

export const CONTENT_TREE: ContentNode = {
  "slug": "content",
  "name": "Content",
  "path": "/finder",
  "kind": "folder",
  "size": 0,
  "modified": "2026-09-07",
  "children": []
};
