#!/usr/bin/env node
/**
 * build-tokens.mjs
 *
 * Reads tokens.json (produced by extract-tokens.swift) and emits:
 *   - tokens.css          CSS custom properties, light + dark
 *   - tailwind.tokens.js  Tailwind theme extension
 *
 * Usage:  node build-tokens.mjs
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, "tokens.json"), "utf8"));

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

/**
 * Starting-point blur radii, in px, keyed by material.
 *
 * These are NOT extracted — NSVisualEffectView's backdrop blur is composited
 * by the window server and cannot be read programmatically. They are
 * hand-seeded approximations meant to be tuned visually against a real Tahoe
 * window. See README.md for the calibration procedure.
 */
const BLUR_SEED = {
  titlebar: 30, selection: 20, menu: 50, popover: 50, sidebar: 50,
  headerView: 30, sheet: 50, windowBackground: 30, hudWindow: 50,
  fullScreenUI: 30, toolTip: 50, contentBackground: 30,
  underWindowBackground: 50, underPageBackground: 30,
};

/* ------------------------------------------------------------------ CSS -- */

function colorVars(scheme) {
  const lines = [];
  for (const [name, v] of Object.entries(tokens.colors[scheme])) {
    if (Array.isArray(v)) {
      v.forEach((c, i) => lines.push(`  --color-${kebab(name)}-${i}: ${c.css};`));
    } else if (v.css) {
      lines.push(`  --color-${kebab(name)}: ${v.css};`);
    }
  }
  return lines.join("\n");
}

function materialVars(scheme) {
  const lines = [];
  for (const [name, m] of Object.entries(tokens.materials[scheme] ?? {})) {
    if (!m?.tint) continue;
    lines.push(`  --material-${kebab(name)}-tint: ${m.tint.css};`);
    lines.push(`  --material-${kebab(name)}-blur: ${BLUR_SEED[name] ?? 30}px;`);
  }
  return lines.join("\n");
}

function typeVars() {
  const lines = [];
  for (const [name, t] of Object.entries(tokens.typography.ramp)) {
    const k = kebab(name);
    lines.push(`  --text-${k}-size: ${t.sizePt}px;`);
    lines.push(`  --text-${k}-line: ${t.lineHeightPt}px;`);
    lines.push(`  --text-${k}-weight: ${t.cssWeight};`);
  }
  lines.push(`  --font-sans: ${tokens.typography.recommendedCSSStack};`);
  lines.push(`  --font-mono: ${tokens.typography.recommendedMonoCSSStack};`);
  return lines.join("\n");
}

function metricVars() {
  const lines = [];
  for (const [control, sizes] of Object.entries(tokens.controlMetrics)) {
    for (const [size, m] of Object.entries(sizes)) {
      lines.push(`  --${kebab(control)}-${size}-height: ${m.heightPt}px;`);
    }
  }
  return lines.join("\n");
}

const css = `/* AUTO-GENERATED by build-tokens.mjs — do not edit by hand.
 * Source: ${tokens._meta.osVersion} via extract-tokens.swift
 * Generated: ${tokens._meta.generatedAt}
 *
 * Blur radii are hand-seeded approximations, not extracted values.
 * Calibrate them visually — see README.md.
 */

:root {
${typeVars()}

${metricVars()}

  /* light (default) */
${colorVars("light")}

${materialVars("light")}
}

@media (prefers-color-scheme: dark) {
  :root {
${colorVars("dark")}

${materialVars("dark")}
  }
}

/* Explicit overrides win over the media query in both directions. */
:root[data-theme="dark"] {
${colorVars("dark")}

${materialVars("dark")}
}

:root[data-theme="light"] {
${colorVars("light")}

${materialVars("light")}
}

/* Glass surface helper. Pair a material tint with its blur.
 * Usage: <div class="tahoe-glass" style="--m: sidebar"> ... */
.tahoe-glass {
  backdrop-filter: blur(var(--glass-blur, 30px)) saturate(180%);
  -webkit-backdrop-filter: blur(var(--glass-blur, 30px)) saturate(180%);
  background-color: var(--glass-tint, var(--color-window-background));
}
`;

writeFileSync(join(here, "tokens.css"), css);

/* ------------------------------------------------------------- Tailwind -- */

const twColors = {};
for (const name of Object.keys(tokens.colors.light)) {
  if (Array.isArray(tokens.colors.light[name])) continue;
  twColors[kebab(name)] = `var(--color-${kebab(name)})`;
}

const twFontSize = {};
for (const [name, t] of Object.entries(tokens.typography.ramp)) {
  twFontSize[kebab(name)] = [
    `var(--text-${kebab(name)}-size)`,
    {
      lineHeight: `var(--text-${kebab(name)}-line)`,
      fontWeight: `var(--text-${kebab(name)}-weight)`,
    },
  ];
}

const twHeight = {};
for (const [control, sizes] of Object.entries(tokens.controlMetrics)) {
  for (const size of Object.keys(sizes)) {
    twHeight[`${kebab(control)}-${size}`] =
      `var(--${kebab(control)}-${size}-height)`;
  }
}

const tw = `// AUTO-GENERATED by build-tokens.mjs — do not edit by hand.
// Source: ${tokens._meta.osVersion}
//
// Usage in tailwind.config.ts:
//   import tahoe from "./design-tokens/tailwind.tokens.js";
//   export default { theme: { extend: tahoe } };

export default ${JSON.stringify(
  {
    colors: twColors,
    fontSize: twFontSize,
    height: twHeight,
    fontFamily: {
      sans: ["var(--font-sans)"],
      mono: ["var(--font-mono)"],
    },
  },
  null,
  2
)};
`;

writeFileSync(join(here, "tailwind.tokens.js"), tw);

const nColors = Object.keys(twColors).length;
const nMaterials = Object.keys(tokens.materials.light ?? {}).length;
console.log(
  `✓ tokens.css + tailwind.tokens.js\n` +
    `  ${nColors} colors × 2 schemes · ${nMaterials} materials · ` +
    `${Object.keys(tokens.typography.ramp).length} type styles`
);
