// Walks content/ and emits system/content/generated.ts — the tree Finder renders.
//
// Finder is a client component and cannot touch the filesystem, so the walk runs
// at build time and its result is bundled. Run via `npm run content`; `prebuild`
// does it automatically.
//
// Frontmatter parsing lives in ./frontmatter.mjs so it can be unit tested.

import { readFileSync, readdirSync, statSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, relative, extname, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { displayName, parseFrontmatter } from "./frontmatter.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT_DIR = join(ROOT, "content");
const OUT_FILE = join(ROOT, "system", "content", "generated.ts");

const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"]);
const WORDS_PER_BYTE = 6; // rough prose-to-bytes ratio for a plausible Finder size column

function kindFor(extension) {
  if (extension === ".pdf") return "pdf";
  if (IMAGE_EXTENSIONS.has(extension)) return "image";
  return "document";
}

function walk(absoluteDir, routePrefix) {
  const entries = readdirSync(absoluteDir)
    .filter((entry) => !entry.startsWith("."))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

  const children = [];

  for (const entry of entries) {
    const absolute = join(absoluteDir, entry);
    const stats = statSync(absolute);

    if (stats.isDirectory()) {
      children.push(buildFolder(absolute, entry, `${routePrefix}/${entry}`));
      continue;
    }

    if (entry === "index.mdx") continue; // consumed as the parent's metadata

    const extension = extname(entry).toLowerCase();
    const slug = entry.slice(0, -extension.length || undefined);
    const kind = kindFor(extension);
    const node = {
      slug,
      name: displayName(slug),
      path: `${routePrefix}/${slug}`,
      kind,
      size: stats.size,
      modified: stats.mtime.toISOString().slice(0, 10),
    };

    if (kind === "document") {
      const { data, body } = parseFrontmatter(readFileSync(absolute, "utf8"));
      if (typeof data.title === "string") node.name = data.title;
      node.body = body.trim();
      node.size = Math.round(body.trim().split(/\s+/).filter(Boolean).length * WORDS_PER_BYTE);
    } else {
      // Assets live in public/content/ mirroring their content/ path
      node.assetUrl = `/content${relative(CONTENT_DIR, absolute).split("\\").join("/").replace(/^/, "/")}`;
    }

    children.push(node);
  }

  return children;
}

function buildFolder(absoluteDir, slug, routePrefix) {
  const node = {
    slug,
    name: displayName(slug),
    path: routePrefix,
    kind: "folder",
    size: 0,
    modified: statSync(absoluteDir).mtime.toISOString().slice(0, 10),
  };

  const indexPath = join(absoluteDir, "index.mdx");
  if (existsSync(indexPath)) {
    const { data, body } = parseFrontmatter(readFileSync(indexPath, "utf8"));
    node.meta = data;
    if (typeof data.title === "string") node.name = data.title;
    if (typeof data.year === "number") node.modified = `${data.year}-01-01`;
    if (body.trim()) node.body = body.trim();
  }

  node.children = walk(absoluteDir, routePrefix);
  node.size = node.children.reduce((total, child) => total + child.size, 0);
  return node;
}

function main() {
  const tree = existsSync(CONTENT_DIR)
    ? { slug: "content", name: "Content", path: "/finder", kind: "folder", size: 0, modified: new Date().toISOString().slice(0, 10), children: walk(CONTENT_DIR, "/finder") }
    : { slug: "content", name: "Content", path: "/finder", kind: "folder", size: 0, modified: new Date().toISOString().slice(0, 10), children: [] };

  tree.size = (tree.children ?? []).reduce((total, child) => total + child.size, 0);

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(
    OUT_FILE,
    `// GENERATED by scripts/build-content.mjs — do not edit.\n` +
      `// Regenerate with \`npm run content\`.\n\n` +
      `import type { ContentNode } from "./types";\n\n` +
      `export const CONTENT_TREE: ContentNode = ${JSON.stringify(tree, null, 2)};\n`
  );

  const projects = (tree.children ?? []).flatMap((child) => child.children ?? []).filter((child) => child.meta);
  console.log(`content: ${projects.length} project(s) -> ${relative(ROOT, OUT_FILE)}`);
}

main();
